### ISSUE TITLE
[Scale]: 357

### ISSUE THREAD

**Issue by fedorovanatolij** [papauorg/levelmeter#7]
### Is new

- [X] The scale I request is not yet available.

### Container form

cylinder

### Length Unit

mm

### Volume unit

l

### Inner diameter

357

### Container height

360

### Min. Volume

1

### Max. Volume

30

### Description

Scale 357 mm

**Comment by papauorg** [comment]
I edited your request to include a Max Volume. This allowed the automatic PR creation for your scale which is now merged and ready to be used.
